CREATE DATABASE cake_shop_db;
GO

USE cake_shop_db;
GO

CREATE TABLE Categories (
    Id INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL
);

CREATE TABLE Biscuits (
    Id INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    ExtraPrice DECIMAL(10,2) NOT NULL DEFAULT 0
);

CREATE TABLE Creams (
    Id INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    ExtraPrice DECIMAL(10,2) NOT NULL DEFAULT 0
);

CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    Phone NVARCHAR(20),
    Role NVARCHAR(20) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE Cakes (
    Id INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(500),
    BasePrice DECIMAL(10,2) NOT NULL,
    PhotoUrl NVARCHAR(500),
    CategoryId INT FOREIGN KEY REFERENCES Categories(Id),
    IsAvailable BIT NOT NULL DEFAULT 1,
    Weight NVARCHAR(50) NULL,
    IsCustomizable BIT NOT NULL DEFAULT 0,
    Ingredients NVARCHAR(500) NULL
);

CREATE TABLE Orders (
    Id INT PRIMARY KEY IDENTITY,
    ClientId INT FOREIGN KEY REFERENCES Users(Id),
    Note NVARCHAR(500),
    TotalPrice DECIMAL(10,2) NOT NULL,
    Status NVARCHAR(50) DEFAULT 'Pending',
    PaymentStatus NVARCHAR(50) DEFAULT 'Unpaid',
    CreatedAt DATETIME DEFAULT GETDATE(),
    DeliveryDate DATETIME
);

CREATE TABLE OrderItems (
    Id INT PRIMARY KEY IDENTITY,
    OrderId INT FOREIGN KEY REFERENCES Orders(Id),
    CakeId INT FOREIGN KEY REFERENCES Cakes(Id),
    BiscuitId INT FOREIGN KEY REFERENCES Biscuits(Id) NULL,
    CreamId INT FOREIGN KEY REFERENCES Creams(Id) NULL,
    Quantity INT NOT NULL DEFAULT 1,
    ItemPrice DECIMAL(10,2) NOT NULL
);

CREATE TABLE SavedCakes (
    Id INT PRIMARY KEY IDENTITY,
    ClientId INT FOREIGN KEY REFERENCES Users(Id),
    CakeId INT FOREIGN KEY REFERENCES Cakes(Id),
    SavedAt DATETIME DEFAULT GETDATE()
);